<a href="https://colab.research.google.com/github/Skystar728/pdm12/blob/main/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [ ]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)    # numpy array를 리턴
# summarize the array content
print(data)
# summarize the array shape
print(data.shape)  # 5번줄이 없으면 AttributeError: 'list' object has no attribute 'shape'
                   # 리스트 계체는 shape(데이터 크기 구조등을 볼때 사용)라는 속성이 없음

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# data.shape # Error!
# convert to a numpy array
data = asarray(data)
# step through rows
for row in range(data.shape[0]):    # shape[] data[] 할경우 SyntaxError: invalid syntax
	print(data[row])

[1 2 3]
[4 5 6]


In [ ]:
data.shape ,data.shape[0], data.shape[1]
# 2행 3열    #행?                #열?

((2, 3), 2, 3)

## Print columns

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col]) #col 열 첫번째 열에 있는 전부다

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


---

## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column. 0이면 세로
- axis=1: Apply operation row-wise, across all columns for each row. 1이면 가로

In [ ]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None) # data.sum() 을 할경우 배열의 모든 항목을 더함(결과 =) axis 기초값이 None임
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [ ]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis = 0) # 세로 값으로 합함
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [ ]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis = 1) # 가로 값으로 합함
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


---

## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [DIY: 도전하기]

- 3차원 배열을 리스트로부터 만드시오.
- [참고: numpy_sum_axis](http://taewan.kim/post/numpy_sum_axis/)

In [ ]:
# Make 3d-array in numpy 3열 3행
'''
data = [[1,2,3], [4,5,6]]
'''

In [ ]:
import numpy as np
arr = np.arange(0, 3*3*3)
data = arr.reshape([3,3,3])
print(data)
print(data.sum(axis=None))
print(data.sum(axis=0))
print(data.sum(axis=1))
print(data.sum(axis=2))
print(data.sum(axis=(0,1)))
print(data.sum(axis=(0,2)))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
351
[[27 30 33]
 [36 39 42]
 [45 48 51]]
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
[108 117 126]
[ 90 117 144]
